"""Render the offline matched-half GRU-versus-Q likelihood report."""

from __future__ import annotations

import json
import math
import statistics
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


STUDY = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(STUDY.parent / "util"))
from plot_style import apply_presentation_style, t975  # noqa: E402


DATA = STUDY / "analysis" / "matched_half_results.json"
FIGURE = STUDY / "analysis" / "fig_matched_half_likelihood.png"
REPORT = STUDY / "analysis" / "reports" / "r1-matched-half-gru-vs-q.md"
START = "<!-- BEGIN result-1 -->"
END = "<!-- END result-1 -->"
DS = (10, 30, 100, 300, 614)
DATASET_LABELS = {
    "grossman": "Grossman mouse",
    "chen": "Chen mouse",
    "zid": "Zid human",
}
COLORS = {"grossman": "#4C72B0", "chen": "#55A868", "zid": "#C44E52"}


def _by_d(rows: list[dict]) -> dict[int, list[dict]]:
    grouped = defaultdict(list)
    for row in rows:
        grouped[int(row["nominal_D"])].append(row)
    if set(grouped) != set(DS) or any(len(grouped[d]) != 3 for d in DS):
        raise AssertionError("Each dataset must contain exactly three seeds at every source D")
    return {d: sorted(grouped[d], key=lambda row: row["seed"]) for d in DS}


def _metric(row: dict, key: str = "normalized_likelihood") -> float:
    return float(row["metrics"][key])


def _mean_sd(values: list[float]) -> tuple[float, float]:
    return statistics.mean(values), statistics.stdev(values)


def _paired_stats(q: dict, rows: list[dict]) -> dict:
    q_subjects = q["metrics"]["per_subject_mean_log_likelihood_nats"]
    gru_by_seed = [
        row["metrics"]["per_subject_mean_log_likelihood_nats"]
        for row in rows
    ]
    if any(set(seed) != set(q_subjects) for seed in gru_by_seed):
        raise AssertionError("GRU/Q per-subject metric sets do not align")
    deltas = []
    for subject_id, q_value in q_subjects.items():
        gru_mean = statistics.mean(
            seed[subject_id] for seed in gru_by_seed
        )
        deltas.append(gru_mean - float(q_value))
    mean = statistics.mean(deltas)
    sem = statistics.stdev(deltas) / math.sqrt(len(deltas))
    return {
        "n_subjects": len(deltas),
        "mean_delta_nats_per_trial": mean,
        "ci95_low": mean - t975(len(deltas)) * sem,
        "ci95_high": mean + t975(len(deltas)) * sem,
        "fraction_gru_better": sum(value > 0 for value in deltas) / len(deltas),
    }


def _plot(data: dict) -> None:
    apply_presentation_style()
    fig, axes = plt.subplots(1, 3, figsize=(13.2, 4.1), constrained_layout=True)
    for axis, (dataset_name, dataset) in zip(axes, data["datasets"].items()):
        grouped = _by_d(dataset["gru"])
        means, sems = [], []
        for d in DS:
            values = [_metric(row) for row in grouped[d]]
            means.append(statistics.mean(values))
            sems.append(statistics.stdev(values) / math.sqrt(len(values)))
            axis.scatter([d] * len(values), values, color=COLORS[dataset_name], alpha=0.45, s=30)
        axis.errorbar(
            DS,
            means,
            yerr=sems,
            color=COLORS[dataset_name],
            marker="o",
            capsize=3,
            label="GRU mean ± SEM (3 seeds)",
        )
        q_value = _metric(dataset["q"])
        axis.axhline(q_value, color="#333333", linestyle="--", label="Q-learning")
        axis.set_xscale("log")
        axis.set_xticks(DS, [str(d) for d in DS])
        axis.set_title(DATASET_LABELS[dataset_name])
        axis.set_xlabel("Source subjects D")
        axis.set_ylabel("Held-out normalized likelihood")
        axis.grid(axis="y", alpha=0.2)
    axes[0].legend(frameon=False, fontsize=11)
    fig.savefig(FIGURE, bbox_inches="tight")
    plt.close(fig)


def _result_block(data: dict) -> str:
    lines = [
        "[regenerated by `analysis/report_matched_half.py` — do not edit by hand]",
        "",
        "![Held-out normalized likelihood by source D](../fig_matched_half_likelihood.png)",
        "",
        "### Trial-pooled held-out likelihood",
        "",
        "Values are Q-learning or GRU mean ± SD across the three independently trained source cores.",
        "",
        "| target dataset | Q-learning | GRU D=10 | D=30 | D=100 | D=300 | D=614 |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    paired_rows = []
    pooled = {}
    for dataset_name, dataset in data["datasets"].items():
        grouped = _by_d(dataset["gru"])
        cells = []
        pooled[dataset_name] = {}
        for d in DS:
            mean, sd = _mean_sd([_metric(row) for row in grouped[d]])
            pooled[dataset_name][d] = mean
            cells.append(f"{mean:.5f} ± {sd:.5f}")
            paired_rows.append((dataset_name, d, _paired_stats(dataset["q"], grouped[d])))
        lines.append(
            f"| {DATASET_LABELS[dataset_name]} | **{_metric(dataset['q']):.5f}** | "
            + " | ".join(cells)
            + " |"
        )

    lines += [
        "",
        "### Bottom line",
        "",
        f"- **Grossman mouse:** GRU is above Q at every source D and rises from "
        f"{pooled['grossman'][10]:.5f} at D=10 to {pooled['grossman'][614]:.5f} at D=614 "
        f"(D=614 minus Q: {pooled['grossman'][614] - _metric(data['datasets']['grossman']['q']):+.5f}).",
        f"- **Chen mouse:** the mean GRU is below Q at D=10/30, crosses above it at D=100, "
        f"and reaches {pooled['chen'][614]:.5f} at D=614 "
        f"(minus Q: {pooled['chen'][614] - _metric(data['datasets']['chen']['q']):+.5f}).",
        f"- **Zid human:** trial-pooled GRU is above Q at every D and peaks at D=300 "
        f"({pooled['zid'][300]:.5f}); D=614 remains "
        f"{pooled['zid'][614] - _metric(data['datasets']['zid']['q']):+.5f} above Q, but the "
        "subject-balanced comparison below is heterogeneous.",
        "",
        "### Subject-balanced paired comparison",
        "",
        "Each value is the per-subject GRU mean log-likelihood averaged across source seeds minus "
        "that subject's Q-learning value. Positive favors GRU.",
        "",
        "| target dataset | source D | Δ log likelihood (nats/trial) | 95% CI | subjects GRU better |",
        "|---|---:|---:|---:|---:|",
    ]
    for dataset_name, d, stats in paired_rows:
        lines.append(
            f"| {DATASET_LABELS[dataset_name]} | {d} | "
            f"{stats['mean_delta_nats_per_trial']:+.5f} | "
            f"[{stats['ci95_low']:+.5f}, {stats['ci95_high']:+.5f}] | "
            f"{stats['fraction_gru_better']:.0%} ({stats['n_subjects']} subjects) |"
        )

    actual_ds = {
        d: sorted({row["actual_D"] for dataset in data["datasets"].values() for row in dataset["gru"] if row["nominal_D"] == d})
        for d in DS
    }
    lines += [
        "",
        "### Verification",
        "",
        "- Every target dataset has 15 finished GRU cells (5 source sizes × 3 seeds) and one Q run.",
        "- GRU and Q prediction files have identical ordered `(subject, session, trial, choice)` keys "
        "within each target dataset; only the model probabilities differ.",
        "- Grossman and Chen use odd-positioned sessions for adaptation and even-positioned sessions "
        "for test. Zid uses trials 0–149 for adaptation and 150–299 for test, with prefix replay only "
        "to establish state before suffix scoring.",
        "- Nominal source D is the plotted axis. Realized source-subject counts were "
        + ", ".join(f"D={d}: {actual_ds[d]}" for d in DS)
        + ".",
        "- Q-learning has one fitted baseline per target dataset, so it has no source-training-seed error bar.",
    ]
    return "\n".join(lines)


def main() -> None:
    data = json.loads(DATA.read_text())
    if not all(item["alignment"]["exact_ordered_trial_keys"] for item in data["datasets"].values()):
        raise AssertionError("Frozen input does not prove exact GRU/Q trial alignment")
    _plot(data)
    block = _result_block(data)
    text = REPORT.read_text()
    start_end = text.index(START) + len(START)
    end_start = text.index(END, start_end)
    REPORT.write_text(text[:start_end] + "\n" + block + "\n" + text[end_start:])
    print(f"Wrote {FIGURE} and {REPORT}")


if __name__ == "__main__":
    main()
