type: gru

_target_: model_trainers.gru_trainer.GruTrainer

architecture:
  hidden_size: 16
  num_layers: 1

training:
  lr: 1e-3
  n_steps: 20
  loss: categorical
  loss_param: 1
  max_grad_norm: 1.0
  checkpoint_every_n_steps: 10
  checkpoint_eval_on_eval_split: true
  checkpoint_log_eval_to_wandb: true
  checkpoint_plot_split_examples_every_n: 10
  checkpoint_save_output_df_every_n: 0
  checkpoint_log_split_examples_to_wandb: true
  checkpoint_keep_media_files: true
  checkpoint_run_heldout_eval: true
  checkpoint_include_final_in_heldout: true
  save_output_df: true
  
run_name_component: gru_H${.architecture.hidden_size}