type: gru

_target_: model_trainers.gru_trainer.GruTrainer

architecture:
  hidden_size: 16
  num_layers: 1

  multisubject: true
  subject_embedding_size: 4
  subject_embedding_init: zeros   # zeros | small_random | subject_count_scaled_random

training:
  lr: 1e-3
  n_steps: 20
  loss: categorical
  loss_param: 1
  max_grad_norm: 1.0

  checkpoint_every_n_steps: 10
  checkpoint_eval_on_train_split: true
  checkpoint_eval_on_eval_split: true
  checkpoint_log_train_to_wandb: true
  checkpoint_log_eval_to_wandb: true
  checkpoint_plot_split_examples_every_n: 10
  checkpoint_log_split_examples_to_wandb: true

  checkpoint_run_heldout_eval: true
  checkpoint_include_final_in_heldout: true

  initialization_eval_before_training: true  # run/log checkpoint-style eval before training
  
  save_output_df: true
  checkpoint_save_output_df_every_n: 0
  checkpoint_keep_media_files: false
  
run_name_component: gru_H${.architecture.hidden_size}