#!/usr/bin/env bash
set -ex

HYDRA_OVERRIDES="$1"

echo "[dispatcher] hydra overrides: ${HYDRA_OVERRIDES}"

# IMPORTANT: no quotes here, so the shell re-splits into args
python -u run_capsule.py ${HYDRA_OVERRIDES}