"""Top level run script for generating a configuration artifact.

This entry point uses Hydra to compose configurations from the files under
`code/config/`. You can invoke it directly with Python or via the CO's input arguments
(which passes the arguments via the "run" file).

Examples (direct Python invocation)
----------------------------------
1. Default single run with the default parameters (data=mice, model=disrnn)
    Uses the defaults declared in `config/config.yaml`:
    ```bash
    python code/run_capsule.py
    ```
    Explicit form:
    ```bash
    python code/run_capsule.py data=mice model=disrnn
    ```

2. Synthetic data generated by an RL agent performing an uncoupled_block task
    Override the top-level data source and model; specify nested synthetic groups:
    ```bash
    python code/run_capsule.py data=synthetic data.synthetic.agent=rl data.synthetic.task=uncoupled_block model=baseline_rl
    ```

3. Hydra multirun sweep over model penalties beta and training learning rate
    Use `-m` (or `--multirun`) to launch a Cartesian product of overrides:
    ```bash
    python code/run_capsule.py -m model.penalties.beta=0.0001,0.001,0.01 model.training.lr=0.0001,0.001
    ```
    Results will be placed under `results/` using Hydra-generated job IDs.


Additional notes
----------------
* All composed configurations are serialized to JSON at `.hydra/config.json` inside the run directory.
* To call programmatically from Python:
  ```python
  from run_capsule import generate_jobs_with_args
  generate_jobs_with_args(["data=mice", "model=disrnn", "job_id=42"])
  ```
"""

import json
import logging
import sys
from pathlib import Path

import hydra
from omegaconf import DictConfig, OmegaConf

from util import dictconfig_to_json

logger = logging.getLogger(__name__)


@hydra.main(version_base=None, config_path="config", config_name="config")
def generate_jobs(cfg: DictConfig) -> None:
    """Main run function that loads Hydra config and saves to results/jobs"""
    
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        stream=sys.stdout,
        format="%(levelname)s:%(asctime)s:%(filename)s:%(lineno)d: %(message)s",
        datefmt="%Y-%m-%d %H-%M-%S",
    )
    
    logger.info("Loaded Hydra configuration")
    logger.info(OmegaConf.to_yaml(cfg))
    
    # Convert config to JSON-serializable dict
    config_dict = dictconfig_to_json(cfg)
    
    # Save config as JSON inside the hydra run directory
    run_dir = Path.cwd()
    config_path = run_dir / ".hydra/config.json"
    with open(config_path, "w") as f:
        json.dump(config_dict, f, indent=2)
    
    logger.info(f"Saved configuration to {config_path}")


def generate_jobs_with_args(override_list: list[str]):
    """Programmatic entry point."""
    sys.argv = ["run_capsule.py"] + override_list
    generate_jobs()

if __name__ == "__main__":
    # Controled by input args
    generate_jobs()
    
    # Overwrite by python code
    #generate_jobs_with_args(["data=mice", "model=disrnn"])