#!/usr/bin/env python
"""Regenerate the script-owned regions of analysis/reports/r*.md from scaling.json.

Contract (docs/posthoc-analysis.md): each report's ``<!-- BEGIN result-N -->`` /
``<!-- END result-N -->`` block is owned by this script; prose outside the markers
is human-edited and never touched. Idempotent: running twice produces identical files.

    python update_reports.py            # reads analysis/scaling.json, rewrites r1/r2 blocks
    (also invoked automatically at the end of scaling.py's main())
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORTS = HERE / "reports"
HS = [16, 64, 128, 256]
DS = [10, 30, 100, 614]


def _fmt(v, nd=5):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "—"


def _cell(grid, D, H):
    return grid.get(f"{D}x{H}")


def _block_r1(data):
    """LR-engaged: 3-way matches the 2-way choice ceiling and scales with D."""
    grid = data["grid"]
    lines = [
        "[regenerated by `analysis/update_reports.py` — do not edit by hand]",
        "",
        "![3-way L/R-engaged scaling](../fig_scaling.png)",
        "",
        "*Held-out conditional L/R likelihood on **engaged trials** vs # training mice (D), "
        "per hidden size H. Solid = 3-way (L/R/ignore) model; faded dashed = 2-way "
        "reference from `01-gru-scaling-law`. Error bars: SEM (n=3 seeds/cell).*",
        "",
        "Mean held-out L/R-engaged likelihood (3-way model):",
        "",
        "| H | D=10 | D=30 | D=100 | D=614 | Δ (D10→D614) |",
        "|---|---|---|---|---|---|",
    ]
    for H in HS:
        vals = []
        for D in DS:
            c = _cell(grid, D, H)
            vals.append(c["LR_engaged"]["mean"] if c else None)
        d10, d614 = vals[0], vals[-1]
        delta = f"+{(d614 - d10):.4f}" if (d10 and d614) else "—"
        cells = " | ".join(_fmt(v) for v in vals)
        lines.append(f"| {H} | {cells} | {delta} |")
    # headline numbers
    best = _cell(grid, 614, 256)
    lines += [
        "",
        f"- **The 3-way head costs nothing on choice prediction.** L/R-engaged sits on or "
        f"above the 2-way reference at every (H, D) — adding the ignore class does not "
        f"degrade choice likelihood.",
        f"- **Scaling is capacity-dependent.** H=16 flattens early "
        f"({_fmt(_cell(grid,10,16)['LR_engaged']['mean'],4)}→{_fmt(_cell(grid,614,16)['LR_engaged']['mean'],4)}), "
        f"while H≥64 keeps climbing through D=614; best cell H=256/D=614 = "
        f"**{_fmt(best['LR_engaged']['mean'],5) if best else '—'}** "
        f"(SEM {_fmt(best['LR_engaged']['sem'],5) if best else '—'}), still not plateaued.",
        "",
        f"Source W&B groups: {', '.join('`'+g+'`' for g in data['_meta']['wandb_groups']) or '—'}.",
    ]
    return "\n".join(lines)


def _block_r2(data):
    """Ignore-class detection: PR-AUC and recall vs D."""
    grid = data["grid"]
    lines = [
        "[regenerated by `analysis/update_reports.py` — do not edit by hand]",
        "",
        "![ignore detection scaling](../fig_scaling.png)",
        "",
        "*Ignore-class detection on held-out mice vs D (middle + right panels of "
        "`fig_scaling.png`). PR-AUC is the headline detection metric (robust to the "
        "~5–10% ignore base rate); recall characterises the operating point.*",
        "",
        "Mean ignore-class **PR-AUC** (held-out):",
        "",
        "| H | D=10 | D=30 | D=100 | D=614 |",
        "|---|---|---|---|---|",
    ]
    for H in HS:
        cells = " | ".join(_fmt((_cell(grid, D, H) or {}).get("ignore_pr_auc", {}).get("mean"), 4)
                           if _cell(grid, D, H) else "—" for D in DS)
        lines.append(f"| {H} | {cells} |")
    lines += ["", "Mean ignore-class **recall** (held-out):", "",
              "| H | D=10 | D=30 | D=100 | D=614 |", "|---|---|---|---|---|"]
    for H in HS:
        cells = " | ".join(_fmt((_cell(grid, D, H) or {}).get("ignore_recall", {}).get("mean"), 4)
                           if _cell(grid, D, H) else "—" for D in DS)
        lines.append(f"| {H} | {cells} |")
    # headline numbers derived from the grid (not hardcoded)
    def _pr(D, H):
        c = _cell(grid, D, H)
        return c["ignore_pr_auc"]["mean"] if c else None
    def _rc(D, H):
        c = _cell(grid, D, H)
        return c["ignore_recall"]["mean"] if c else None
    # PR-AUC D-range across the larger models (H>=64), min at D=10 to max at D=614
    big_lo = [v for v in (_pr(10, H) for H in (64, 128, 256)) if v is not None]
    big_hi = [v for v in (_pr(614, H) for H in (64, 128, 256)) if v is not None]
    pr_lo = min(big_lo) if big_lo else None
    pr_hi = max(big_hi) if big_hi else None
    # recall ceiling: the max recall anywhere in the grid
    all_rc = [_rc(D, H) for H in HS for D in DS if _rc(D, H) is not None]
    rc_max = max(all_rc) if all_rc else None
    lines += [
        "",
        f"- **Ignore detection is well above chance and improves with D.** For the "
        f"larger models (H≥64), PR-AUC rises ~{_fmt(pr_lo,3)}→{_fmt(pr_hi,3)} from "
        f"D=10 to D=614, far above the ~0.05–0.10 no-skill base rate.",
        f"- **Recall stays capped near {_fmt(rc_max,2)}** even at D=614 — the model "
        f"is consistently conservative on ignore trials regardless of scale (a real "
        f"detection ceiling, not a data-scarcity artifact).",
        "",
        f"Source W&B groups: {', '.join('`'+g+'`' for g in data['_meta']['wandb_groups']) or '—'}.",
    ]
    return "\n".join(lines)


BLOCKS = {"result-1": _block_r1, "result-2": _block_r2}


def _replace_block(text, marker, body):
    pat = re.compile(
        rf"(<!-- BEGIN {marker} -->\n).*?(\n<!-- END {marker} -->)",
        re.DOTALL,
    )
    if not pat.search(text):
        raise ValueError(f"marker pair for {marker} not found")
    return pat.sub(lambda m: m.group(1) + body + m.group(2), text)


def run(data=None):
    if data is None:
        data = json.loads((HERE / "scaling.json").read_text())
    mapping = {"r1-lr-engaged-scaling.md": "result-1",
               "r2-ignore-detection-scaling.md": "result-2"}
    for fname, marker in mapping.items():
        fp = REPORTS / fname
        text = fp.read_text()
        text = _replace_block(text, marker, BLOCKS[marker](data))
        fp.write_text(text)
    return list(mapping)


if __name__ == "__main__":
    print("updated:", run())
