#!/usr/bin/env python
"""Regenerate the script-owned regions of analysis/reports/r*.md from beta_scan_summary.json.

Contract (docs/posthoc-analysis.md): each report's ``<!-- BEGIN result-N -->`` /
``<!-- END result-N -->`` block is owned by this script; prose outside the markers
is human-edited and never touched. Idempotent.

    python update_reports.py   # reads analysis/beta_scan_summary.json, rewrites r1/r2 blocks
    (also invoked automatically at the end of beta_scan_report.py's main())
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORTS = HERE / "reports"
MULTS = [1, 2, 5, 10]


def _fmt(v, nd=3):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "\u2014"


def _cell(cells, m, b):
    return cells.get(f"m{m}_b{b:g}")


def _block_r1(data):
    """Sparsity: multiplier monotonically closes the interaction bottleneck; families differ."""
    cells = data["cells"]; betas = data["betas"]
    lines = [
        "[regenerated by `analysis/update_reports.py` \u2014 do not edit by hand]",
        "",
        "![bottleneck openness vs multiplier](../fig_bottlenecks_by_mult.png)",
        "",
        "*Total openness \u03a3(1\u2212\u03c3) of each of the six disRNN bottlenecks vs the update-net "
        "latent penalty multiplier, per base \u03b2 (mean\u00b1SEM over seeds/lr). Openness is the "
        "honest absolute scale (~0 = fully closed); `n_eff_open_frac` is deliberately not used "
        "(see [INDEX caveat](INDEX.md)).*",
        "",
        "**Interaction bottleneck (update\u2190latent, the multiplier's target)** \u2014 mean \u03a3(1\u2212\u03c3):",
        "",
        "| base \u03b2 | mult=1 | mult=2 | mult=5 | mult=10 |",
        "|---|---|---|---|---|",
    ]
    for b in betas:
        vals = []
        for m in MULTS:
            c = _cell(cells, m, b)
            vals.append(c["update_net_latent_openness"]["mean"] if c else None)
        lines.append(f"| {b:g} | " + " | ".join(_fmt(v) for v in vals) + " |")
    # headline numbers from the grid
    c34 = _cell(cells, 1, betas[0]); c34b = _cell(cells, 10, betas[0])
    strong = betas[-1]
    cs1 = _cell(cells, 1, strong)
    lines += [
        "",
        "- **The multiplier monotonically closes its target.** At weak \u03b2="
        f"{betas[0]:g}, update\u2190latent openness falls "
        f"{_fmt(c34['update_net_latent_openness']['mean'])}\u2192"
        f"{_fmt(c34b['update_net_latent_openness']['mean'])} from mult=1\u219210 \u2014 monotone, "
        "not U-shaped (an earlier U-shape was an artifact of `n_eff_open_frac`).",
        f"- **Strong \u03b2={strong:g} is already fully closed at every multiplier** "
        f"(\u03a3(1\u2212\u03c3)\u2248{_fmt(cs1['update_net_latent_openness']['mean'])} at mult=1), so the "
        "multiplier has nothing left to compress.",
        "- **The model compensates.** As the multiplier squeezes update\u2190latent, the "
        "update\u2190subject and choice\u2190latent gates OPEN (information reroutes rather than "
        "disappears); the recurrent latent also closes (collateral over-regularization); "
        "update\u2190obs stays the most open; choice\u2190subject is shut throughout.",
        "",
        ("Source W&B groups: " + (', '.join('`'+g+'`' for g in data['_meta']['wandb_groups']) or '\u2014') + "."),
    ]
    return "\n".join(lines)


def _block_r2(data):
    """Held-out transfer: flat across multiplier, set by base beta; no sparsity tax."""
    cells = data["cells"]; betas = data["betas"]
    lines = [
        "[regenerated by `analysis/update_reports.py` \u2014 do not edit by hand]",
        "",
        "![interaction openness + held-out vs multiplier](../fig_mult_axis_heldout.png)",
        "",
        "*Top: interaction-bottleneck openness \u03a3(1\u2212\u03c3) vs multiplier. Bottom: held-out "
        "mouse transfer likelihood vs multiplier, per base \u03b2 (mean\u00b1SEM over seeds/lr).*",
        "",
        "Mean held-out transfer likelihood:",
        "",
        "| base \u03b2 | mult=1 | mult=2 | mult=5 | mult=10 |",
        "|---|---|---|---|---|",
    ]
    allh = []
    for b in betas:
        vals = []
        for m in MULTS:
            c = _cell(cells, m, b)
            v = c["heldout_ll"]["mean"] if c else None
            vals.append(v)
            if v is not None:
                allh.append(v)
        lines.append(f"| {b:g} | " + " | ".join(_fmt(v, 4) for v in vals) + " |")
    rng = (max(allh) - min(allh)) if allh else 0.0
    # weak-beta vs strong-beta means (pooled over mult)
    def _pool(b):
        vs = [_cell(cells, m, b)["heldout_ll"]["mean"] for m in MULTS if _cell(cells, m, b)]
        return sum(vs) / len(vs) if vs else None
    weak, strong = _pool(betas[0]), _pool(betas[-1])
    lines += [
        "",
        f"- **Held-out transfer is flat across the multiplier** \u2014 full range across all 12 "
        f"cells is only ~{_fmt(rng, 3)} LL. Compressing the interaction bottleneck costs "
        "essentially nothing in transfer.",
        f"- **What little structure exists tracks base \u03b2, not multiplier:** weak \u03b2="
        f"{betas[0]:g} pools to {_fmt(weak, 4)} vs strong \u03b2={betas[-1]:g} at {_fmt(strong, 4)} "
        "(strong \u03b2 over-regularizes overall, ~0.005\u20130.01 lower everywhere).",
        "- **Practical read:** mult=2 at weak/moderate \u03b2 is the interpretable sweet spot \u2014 it "
        "compresses the interaction bottleneck substantially while keeping ~1 functional open "
        "channel, at no held-out cost; mult=5/10 over-collapse to zero open channels.",
        "",
        ("Source W&B groups: " + (', '.join('`'+g+'`' for g in data['_meta']['wandb_groups']) or '\u2014') + "."),
    ]
    return "\n".join(lines)


BLOCKS = {"result-1": _block_r1, "result-2": _block_r2}


def _replace_block(text, marker, body):
    pat = re.compile(rf"(<!-- BEGIN {marker} -->\n).*?(\n<!-- END {marker} -->)", re.DOTALL)
    if not pat.search(text):
        raise ValueError(f"marker pair for {marker} not found")
    return pat.sub(lambda m: m.group(1) + body + m.group(2), text)


def run(data=None):
    if data is None:
        data = json.loads((HERE / "beta_scan_summary.json").read_text())
    mapping = {"r1-bottleneck-sparsity-multiplier.md": "result-1",
               "r2-heldout-transfer.md": "result-2"}
    for fname, marker in mapping.items():
        fp = REPORTS / fname
        text = fp.read_text()
        text = _replace_block(text, marker, BLOCKS[marker](data))
        fp.write_text(text)
    return list(mapping)


if __name__ == "__main__":
    print("updated:", run())
