#!/usr/bin/env python
"""Update Result 8 in reports/r8-gru-vs-rl-baseline.md from rl_baseline.json.

Rewrites only the paired GRU-vs-RL table between the BEGIN/END HTML-comment
markers; the markers themselves are preserved so the regenerator can find
them on the next run.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).parent
REPORT = HERE / "reports" / "r8-gru-vs-rl-baseline.md"
RL_JSON = HERE / "rl_baseline.json"
START = "<!-- BEGIN result-8 -->"
END = "<!-- END result-8 -->"

VARIANTS = ("v1", "v2")
DS = (10, 30, 100, 300, 614)


def _wilcoxon(p: float) -> str:
    return f"{p:.1e}".replace("e-0", "e-")


def build_block(data: dict) -> str:
    models = data["models"]
    paired_by_model = data["paired_by_model"]
    best = data["best_model"]
    band = data.get("band_model", "bari")
    # strongest first
    order = sorted(models, key=lambda k: -models[k]["pooled_likelihood_trial_weighted"])

    lines = [
        "[regenerated by `analysis/update_r8.py` — do not edit by hand]",
        "",
        "### The classical-RL suite on the same 149 held-out mice",
        "",
        "| model | agent | pooled LL (trial-wtd) | per-subject mean ± SE | fitted params |",
        "|---|---|---|---|---|",
    ]
    for k in order:
        m = models[k]
        star = " ⭐" if k == best else ""
        lines.append(
            f"| **{m['label']}**{star} | `{m['agent']}` | "
            f"**{m['pooled_likelihood_trial_weighted']:.5f}** | "
            f"{m['per_subject_mean_likelihood']:.4f} ± {m['per_subject_se']:.4f} | "
            f"{len(m['params'].split(','))} |"
        )
    lines += [
        "",
        f"⭐ = strongest classical model. **{models[best]['label']}** is the honest "
        "baseline for \"does the GRU beat classical RL?\".",
        "",
        "> **Reproduction check.** The `bari` arm re-fits the same agent as the original "
        f"`rl-baseline-simple` run (`{data['legacy_bari']['run_id']}`), whose pooled LL was "
        f"**{data['legacy_bari']['pooled_likelihood_trial_weighted']:.5f}**. The new fit differs by "
        f"**{data['legacy_reproduction_delta']:+.5f}** — within differential-evolution "
        "stochasticity, so the suite reproduces the published number.",
        "",
        "### Paired GRU − RL per held-out mouse, per model",
        "",
        "| variant | D | GRU mean | " + " | ".join(f"Δ vs {models[k]['label']}" for k in order) + " |",
        "|---|---|---|" + "---|" * len(order),
    ]
    for var in VARIANTS:
        for D in DS:
            ref = paired_by_model[order[0]]["per_cell"].get(f"{var}_D{D}")
            if ref is None:
                continue
            cells = []
            for k in order:
                c = paired_by_model[k]["per_cell"].get(f"{var}_D{D}")
                cells.append(
                    "—" if c is None else
                    f"{c['mean_delta']:+.5f} ({round(c['frac_gru_wins']*100)}%↑, "
                    f"p={_wilcoxon(c['wilcoxon_p'])})"
                )
            lines.append(f"| {var} | {D:<3} | {ref['gru_mean']:.4f} | " + " | ".join(cells) + " |")

    hero = paired_by_model[best]["per_cell"].get("v2_D614")
    band_cell = paired_by_model[band]["per_cell"].get("v2_D614")
    if hero and band_cell:
        lines += [
            "",
            f"**Headline (v2, D=614).** Against the *strongest* classical model "
            f"({models[best]['label']}) the GRU's margin is **{hero['mean_delta']:+.5f}** "
            f"({round(hero['frac_gru_wins']*100)}% of mice, Wilcoxon p={_wilcoxon(hero['wilcoxon_p'])}). "
            f"The originally-reported margin was measured against {models[band]['label']} "
            f"(**{band_cell['mean_delta']:+.5f}**), which is **not** the strongest classical "
            f"model — so the earlier figure overstated the gap by "
            f"**{abs(band_cell['mean_delta'] - hero['mean_delta']):.5f}** "
            f"({abs(band_cell['mean_delta'] - hero['mean_delta']) / abs(hero['mean_delta']) * 100:.0f}%). "
            "The GRU still wins, on every model and every cell.",
            "",
            f"> **Note on the reference band.** Results 1/4/5/7 draw their RL band from "
            f"**{models[band]['label']}** (`band_model` in `rl_baseline.json`), the model those "
            "figures were originally written against. It is not the strongest baseline; treat "
            "those bands as a *historical* reference and this table as the comparison of record.",
        ]
    return "\n".join(lines)


def update_report(dry_run: bool = False) -> str:
    data = json.loads(RL_JSON.read_text())
    block = build_block(data)
    text = REPORT.read_text()
    start_end = text.index(START) + len(START)
    end_start = text.index(END, start_end)
    updated = text[:start_end] + "\n" + block + "\n" + text[end_start:]
    if not dry_run:
        REPORT.write_text(updated)
    return block


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    block = update_report(dry_run=args.dry_run)
    if args.dry_run:
        print(block)
    else:
        print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
