#!/usr/bin/env python
"""Update Result 8 in reports/r8-gru-vs-rl-baseline.md from rl_baseline.json.

Rewrites only the paired GRU-vs-RL table between the BEGIN/END HTML-comment
markers; the markers themselves are preserved so the regenerator can find
them on the next run.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).parent
REPORT = HERE / "reports" / "r8-gru-vs-rl-baseline.md"
RL_JSON = HERE / "rl_baseline.json"
START = "<!-- BEGIN result-8 -->"
END = "<!-- END result-8 -->"

VARIANTS = ("v1", "v2")
DS = (10, 30, 100, 300, 614)


def _wilcoxon(p: float) -> str:
    return f"{p:.1e}".replace("e-0", "e-")


def build_block(data: dict) -> str:
    per_cell = data["gru_vs_rl_paired"]["per_cell"]
    lines = [
        "[regenerated by `analysis/update_r8.py` — do not edit by hand]",
        "",
        "| variant | D | GRU mean | RL mean | meanΔ (GRU−RL) | %GRU wins | Wilcoxon p |",
        "|---|---|---|---|---|---|---|",
    ]
    for var in VARIANTS:
        for D in DS:
            c = per_cell[f"{var}_D{D}"]
            d_str = f"{D:<3}"
            lines.append(
                f"| {var} | {d_str} | {c['gru_mean']:.4f} | {c['rl_mean']:.4f} | "
                f"{c['mean_delta']:+.5f} | {round(c['frac_gru_wins']*100)}% | "
                f"{_wilcoxon(c['wilcoxon_p'])} |"
            )
    return "\n".join(lines)


def update_report(dry_run: bool = False) -> str:
    data = json.loads(RL_JSON.read_text())
    block = build_block(data)
    text = REPORT.read_text()
    start_end = text.index(START) + len(START)
    end_start = text.index(END, start_end)
    updated = text[:start_end] + "\n" + block + "\n" + text[end_start:]
    if not dry_run:
        REPORT.write_text(updated)
    return block


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    block = update_report(dry_run=args.dry_run)
    if args.dry_run:
        print(block)
    else:
        print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
