#!/usr/bin/env python
"""Regenerate the script-owned regions of analysis/reports/r*.md from timing_scaling.json.

Contract (docs/posthoc-analysis.md): each report's ``<!-- BEGIN result-N -->`` /
``<!-- END result-N -->`` block is owned by this script; prose outside the markers
is human-edited and never touched. Idempotent: running twice produces identical files.

    python update_reports.py     # reads analysis/timing_scaling.json, rewrites r1/r2 blocks
    (also invoked automatically at the end of timing_scaling.py's main())
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPORTS = HERE / "reports"
DS = [10, 30, 100, 300, 614]
TRUST_D = [D for D in DS if D >= 100]
ARMS = ["OFF", "RT", "LICK", "ON", "SHUF"]


def _fmt(v, nd=5):
    return f"{v:.{nd}f}" if isinstance(v, (int, float)) else "\u2014"


def _f1000(v, nd=2):
    return f"{v * 1000:+.{nd}f}" if isinstance(v, (int, float)) else "\u2014"


def _hl(grid, arm, D):
    c = grid[arm][str(D)]["heldout"]
    return c["mean"] if c else None


def _block_r1(data):
    """The decomposition: real flat information effect carried ~98% by licking."""
    grid, dec = data["grid"], data["decomposition"]
    lines = [
        "[regenerated by `analysis/update_reports.py` \u2014 do not edit by hand]",
        "",
        "![block decomposition](../fig_block_decomposition.png)",
        "![information vs width-cost](../fig_threeway.png)",
        "",
        "*Held-out MOUSE likelihood. Five arms \u00d7 D grid, 3 seeds/cell. D\u226430 (shaded, "
        "open markers) is excluded from every estimate \u2014 see r2. Metric: "
        f"`{data['metric']}`.*",
        "",
        "Held-out likelihood by arm \u00d7 D:",
        "",
        "| D | OFF | RT-only | licks-only | both (ON) | shuffled |",
        "|---|---|---|---|---|---|",
    ]
    for D in DS:
        cells = " | ".join(_fmt(_hl(grid, a, D)) for a in ("OFF", "RT", "LICK", "ON", "SHUF"))
        lines.append(f"| {D} | {cells} |")
    lines += [
        "",
        "Decomposition over baseline (\u00d71000 held-out LL):",
        "",
        "| D | RT-only | licks-only | both (net) | information (ON\u2212SHUF) | width cost (SHUF\u2212OFF) |",
        "|---|---|---|---|---|---|",
    ]
    for D in DS:
        d = dec[str(D)]
        lines.append(
            f"| {D} | {_f1000(d.get('rt_gain'))} | {_f1000(d.get('lick_gain'))} | "
            f"{_f1000(d.get('net'))} | {_f1000(d.get('information'))} | {_f1000(d.get('width_cost'))} |"
        )
    # headline numbers, derived (not hardcoded), over the trustworthy D>=100 regime
    def _avg(key):
        vals = [dec[str(D)].get(key) for D in TRUST_D if dec[str(D)].get(key) is not None]
        return sum(vals) / len(vals) if vals else None
    lick, rt, net = _avg("lick_gain"), _avg("rt_gain"), _avg("net")
    info = _avg("information")
    lick_share = f"{lick / net * 100:.0f}%" if (lick and net) else "\u2014"
    rt_share = f"{rt / net * 100:.0f}%" if (rt and net) else "\u2014"
    lines += [
        "",
        f"- **Lick counts carry essentially the whole effect.** At D\u2265100, licks-only "
        f"adds **{_fmt(lick)}** ({lick_share} of the combined **{_fmt(net)}**); RT-only "
        f"adds **{_fmt(rt)}** ({rt_share}).",
        f"- **The information effect is flat, not growing.** ON\u2212shuffled holds at "
        f"~**{_fmt(info)}** across the trustworthy D range; the apparent growth in the "
        f"raw ON\u2212OFF curve is the vanishing input-width overfitting penalty "
        f"(shuffled\u2212OFF), not information scaling with data.",
        f"- **Counter-intuitively, novel variance is not useful variance.** Reaction "
        f"time is near-orthogonal to the existing (prev-choice, prev-reward) inputs yet "
        f"contributes little; lick counts are heavily redundant with prev choice yet "
        f"carry the effect.",
        "",
        f"Source W&B groups: {', '.join('`' + g + '`' for g in data['_meta']['wandb_groups']) or '\u2014'}.",
    ]
    return "\n".join(lines)


def _block_r2(data):
    """Why D<=30 is untrustworthy: best_eval selects on a collapsed within-subject signal."""
    sel = data["selection_diagnostic"]
    lines = [
        "[regenerated by `analysis/update_reports.py` \u2014 do not edit by hand]",
        "",
        "![selection breakdown](../fig_selection_breakdown.png)",
        "",
        "*Held-out scoring uses the best-validation checkpoint "
        "(`best_eval` = argmax within-subject `checkpoint/eval_likelihood`). This panel "
        "shows why that selection is unreliable below D\u2248100.*",
        "",
        "| D | corr(within-subject, held-out) | within-subject seed sd | held-out seed sd |",
        "|---|---|---|---|",
    ]
    for D in DS:
        s = sel[str(D)]
        c = f"{s['corr_within_heldout']:+.2f}" if s["corr_within_heldout"] is not None else "\u2014"
        w = _fmt(s["within_sd"], 4); h = _fmt(s["heldout_sd"], 4)
        lines.append(f"| {D} | {c} | {w} | {h} |")
    lo = sel[str(DS[0])]["corr_within_heldout"]
    hi = sel[str(DS[-1])]["corr_within_heldout"]
    lines += [
        "",
        f"- **The selection signal is broken at small cohorts.** corr(within-subject, "
        f"held-out) across seeds rises from **{_fmt(lo, 2)}** at D={DS[0]} to "
        f"**{_fmt(hi, 2)}** at D={DS[-1]}. Below D\u2248100 the within-subject metric "
        f"`best_eval` selects on is essentially uncorrelated with what we report, so it "
        f"cannot pick a good checkpoint.",
        f"- **Seed noise dwarfs the effect at small D.** At D={DS[0]} the held-out seed "
        f"sd is **{_fmt(sel[str(DS[0])]['heldout_sd'], 4)}** and the within-subject sd "
        f"**{_fmt(sel[str(DS[0])]['within_sd'], 4)}** \u2014 both far above the ~0.0075 "
        f"effect; by D\u2265100 they fall below it.",
        f"- **Consequence.** D\u226430 cells are excluded from every effect estimate "
        f"(drawn as open markers). A future fix is to select checkpoints on held-out LL "
        f"(`best_heldout`) rather than within-subject.",
        "",
        f"Source W&B groups: {', '.join('`' + g + '`' for g in data['_meta']['wandb_groups']) or '\u2014'}.",
    ]
    return "\n".join(lines)


BLOCKS = {"result-1": _block_r1, "result-2": _block_r2}


def _replace_block(text, marker, body):
    pat = re.compile(rf"(<!-- BEGIN {marker} -->\n).*?(\n<!-- END {marker} -->)", re.DOTALL)
    if not pat.search(text):
        raise ValueError(f"marker pair for {marker} not found")
    return pat.sub(lambda m: m.group(1) + body + m.group(2), text)


def run(data=None):
    if data is None:
        data = json.loads((HERE / "timing_scaling.json").read_text())
    mapping = {"r1-block-decomposition.md": "result-1",
               "r2-selection-reliability.md": "result-2"}
    for fname, marker in mapping.items():
        fp = REPORTS / fname
        text = fp.read_text()
        text = _replace_block(text, marker, BLOCKS[marker](data))
        fp.write_text(text)
    return list(mapping)


if __name__ == "__main__":
    print("updated:", run())
